### ISSUE TITLE
better bedrock usability

### ISSUE THREAD

**Issue by abhisantos** [Janschuri/LunaticFamily#1]
Hello,
is there a way to disable the confirmations?
it asks in chat if you want to confirm, but when you click on it nothing happens...
or maybe add another type of confirmation.

also players with bedrock cant click on messages so if there was a way to disable or at least confirm by re-typing the command

thank you

paper 1.20.6

**Comment by abhisantos** [comment]
Also the permission lunaticfamily.adopt is not working for non opped players

**Comment by Janschuri** [comment]
Hi,

Thanks for reporting! You're right, I forgot about the Bedrock players. The syntax should always be like this:

/marry divorce **confirm**

or

"/marry divorce **deny**"


Sometimes you might need to confirm again. For example, if your partner doesn't have enough money for a divorce and you want to take on the payment. In that case, you need to add "force". It would look like this:

"/marry divorce confirm **force**"


I hope this helps. Now that I know, I will try to find a more elegant solution for Bedrock players.

Regarding your permission problem, which commands can't the players perform?

**Comment by Janschuri** [comment]
I fixed the problem with the permissions, and now clickable messages also works in 1.20.6. I have uploaded the new versions to Spigot. You need to update LunaticFamily and LunaticLib.

Regarding the problem with Bedrock, I hope the previous message helps. Disabling the confirmation entirely isn’t a solution because for multiple commands, they are required to provide the player with information about an extra payment or a child that gets adopted. In the future, I would like to find a solution for that. I keep the issue open as an enhancement.

**Comment by abhisantos** [comment]
> I fixed the problem with the permissions, and now clickable messages also works in 1.20.6. I have uploaded the new versions to Spigot. You need to update LunaticFamily and LunaticLib.
> 
> Regarding the problem with Bedrock, I hope the previous message helps. Disabling the confirmation entirely isn’t a solution because for multiple commands, they are required to provide the player with information about an extra payment or a child that gets adopted. In the future, I would like to find a solution for that. I keep the issue open as an enhancement.

Thank you very much!
Yes bedrock players are using the command with confirm now!

**Comment by abhisantos** [comment]
One other thing that i would suggest/ask, if possible, to add placeholders.
Players miss the little heart in chat before the nicknames, as in the other marriage plugin.

**Comment by Janschuri** [comment]
> One other thing that i would suggest/ask, if possible, to add placeholders. Players miss the little heart in chat before the nicknames, as in the other marriage plugin.

I already thought of that. I will turn this into another enhancement issue.

**Comment by Janschuri** [comment]
There is now an option in the config, which turns clickable decision messages into inventory guis, to allow a better bedrock usabilty.

`decision_as_inv_gui: false`
