### ISSUE TITLE
Leaving or joining the server always sends the partner_offline string to your partner

### ISSUE THREAD

**Issue by cosmunn** [Janschuri/LunaticFamily#13]
**Running:**
- LunaticLib 1.1.11
- LunaticFamily 1.2.8
- Purpur 1.21-2274-c3849be (MC: 1.21)

**Description:**
Whenever your partner either leaves or joins the server you will always get the `partner_offline` string. You only get the `partner_online` string when your partner was already online when you joined.
Having a separate line as to when they are already on the server and to when they join the server would also be great, but that's just a suggestion and not part of the problem. And thank you very much for fixing all the bugs I've been finding so far!

![image](https://github.com/user-attachments/assets/fa08ccc9-795c-4779-86df-593b0b50f677)
On this image:
- I joined the server, partner was already on, got the correct `partner_online` string;
- Partner left the server, got the correct `partner_offline` string;
- Partner rejoined the server, got the incorrect `partner_offline` string.

![image](https://github.com/user-attachments/assets/d94e438d-c0a3-4dd5-b230-4b1a122bca69)

**Comment by Janschuri** [comment]
I fixed the bug and added your suggestion in LunaticFamily-1.2.9. You can download it on at spigot. I hope you enjoy it!
