### ISSUE TITLE
LunaticLib 1.1.10 not starting on server version 1.21

### ISSUE THREAD

**Issue by cosmunn** [Janschuri/LunaticFamily#8]
LunaticFamily version 1.2.4
LunaticLib version 1.1.10
Running Purpur 1.21-2257-cb0f04b (MC: 1.21)

LunaticLib 1.1.10 throws an error on startup saying 1.21 is an unsupported version. Using LunaticLib 1.1.8 I am able to start the server normally, and it does not throw the error. I'm reporting the error here since I didn't find a repository for LunaticLib itself.

```
[LunaticLib] Enabling LunaticLib v1.1.10
[LunaticLib] Server version: 1.21-R0.1-SNAPSHOT
[LunaticLib] Error: java.lang.ClassNotFoundException: de.janschuri.lunaticlib.nms.v1_21.VersionImpl
[LunaticLib] Unsupported server version: v1_21
[LunaticLib] Disabling LunaticLib...
[LunaticLib] Disabling LunaticLib v1.1.10
[LunaticLib] LunaticLib disabled.
```

**Comment by Janschuri** [comment]
Hi, thanks for the report, I fixed this Bug in 1.1.11 of LunaticLib.
